import type { ActivityItem, Category, Kpi, LandingProduct, Product, QuickAction, SubscriptionPlan, Testimonial } from "./types";

export const categories: Category[] = [
  { label: "Home Decor", href: "#home", icon: "home" },
  { label: "Food & Drink", href: "#food", icon: "cup" },
  { label: "Beauty", href: "#beauty", icon: "beauty" },
  { label: "Jewelry", href: "#jewelry", icon: "jewelry" },
  { label: "Kids", href: "#kids", icon: "kids" },
];

export const landingProducts: LandingProduct[] = [
  {
    id: "ripple-vase",
    name: "Ripple Ceramic Vase",
    brand: "Sunday Muse",
    price: "$22.00",
    terms: "Net 60",
    ratingCount: 62,
    image: "https://images.unsplash.com/photo-1602872030490-4a484a7b3ba6?auto=format&fit=crop&w=700&q=86",
    alt: "Ripple ceramic vase with green branches",
  },
  {
    id: "amber-candle",
    name: "Amber & Moss Candle",
    brand: "Fieldpar Co.",
    price: "$18.50",
    terms: "Net 60",
    ratingCount: 48,
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=700&q=86",
    alt: "Amber glass candle",
  },
  {
    id: "oat-milk-soap",
    name: "Oat Milk Soap Bar",
    brand: "Wild Earth",
    price: "$6.75",
    terms: "Net 60",
    ratingCount: 73,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=700&q=86",
    alt: "Handmade oat milk soap bar",
  },
  {
    id: "speckled-mug",
    name: "Speckled Mug",
    brand: "Casa Palma",
    price: "$9.25",
    terms: "Net 60",
    ratingCount: 35,
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=86",
    alt: "Speckled ceramic mug",
  },
  {
    id: "facial-oil",
    name: "Nourishing Facial Oil",
    brand: "Herb & Bloom",
    price: "$16.00",
    terms: "Net 60",
    ratingCount: 57,
    image: "https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=700&q=86",
    alt: "Nourishing facial oil dropper bottle",
  },
  {
    id: "storage-basket",
    name: "Seagrass Storage Basket",
    brand: "Madera Collective",
    price: "$24.00",
    terms: "Net 60",
    ratingCount: 41,
    image: "https://images.unsplash.com/photo-1616627561839-074385245ff6?auto=format&fit=crop&w=700&q=86",
    alt: "Seagrass storage basket with folded textile",
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus",
    provider: "AI workspace",
    price: "$0.50",
    billingPeriod: "month",
    badge: "Popular",
    shortDescription: "Premium AI access for everyday writing, research, and productivity.",
    description: "A ready-to-use monthly ChatGPT Plus subscription delivered with setup guidance and support notes.",
    rating: 5,
    ratingCount: 62,
    soldQuantity: 148,
    stockQuantity: 60,
    features: ["Monthly access", "Fast setup assistance", "Usage guidance included", "Replacement support if access stops working"],
    whatYouGet: "Account access details, activation notes, and a support contact for replacement requests during the covered period.",
    deliveryNote: "Delivered to your email or preferred messaging app after order verification.",
    refundSummary: "Free replacement if your subscription stops working during the covered period.",
    thumbnailTone: "bg-[#eee8dd]",
    thumbnail: "/product-art/product-chatgpt-plus.png",
    thumbnailAlt: "Brand-neutral AI chat subscription thumbnail in Zenvy's paper and olive palette",
    brandKind: "chatgpt",
    brandLabel: "ChatGPT",
    brandColor: "#10A37F",
    brandBackground: "#ffffff",
    brandTextColor: "#111111",
    icon: "wand",
    featured: true,
  },
  {
    id: "chatgpt-pro",
    name: "ChatGPT Pro",
    provider: "AI workspace",
    price: "$100",
    billingPeriod: "month",
    badge: "Power plan",
    shortDescription: "Higher-capacity AI access for advanced workflows and frequent usage.",
    description: "A premium monthly ChatGPT Pro plan for customers who need stronger access and priority support.",
    rating: 5,
    ratingCount: 48,
    soldQuantity: 96,
    stockQuantity: 24,
    features: ["Monthly Pro access", "Priority setup queue", "Delivery confirmation", "Replacement support if access stops working"],
    whatYouGet: "Subscription access, verification support, and a replacement request path for the covered month.",
    deliveryNote: "Delivered after order review and payment confirmation.",
    refundSummary: "Free replacement if your subscription stops working during the covered period.",
    thumbnailTone: "bg-[#e6ded2]",
    thumbnail: "/product-art/product-chatgpt-pro.png",
    thumbnailAlt: "Brand-neutral premium AI workspace thumbnail with abstract chat cards",
    brandKind: "chatgpt",
    brandLabel: "ChatGPT",
    brandColor: "#10A37F",
    brandBackground: "#ffffff",
    brandTextColor: "#111111",
    icon: "analytics",
  },
  {
    id: "netflix-standard",
    name: "Netflix Standard",
    provider: "Streaming",
    price: "Price TBA",
    billingPeriod: "month",
    badge: "Placeholder",
    shortDescription: "Standard streaming plan placeholder for the site owner to price.",
    description: "A streaming subscription listing template for Standard-tier access. Final pricing and service terms should be confirmed by the site owner.",
    rating: 5,
    ratingCount: 73,
    soldQuantity: 182,
    stockQuantity: 42,
    features: ["Monthly access", "Standard tier placeholder", "Support handoff", "Replacement policy summary"],
    whatYouGet: "Access instructions and account delivery notes once the owner finalizes plan availability.",
    deliveryNote: "Delivery timing and availability must be confirmed before publishing.",
    refundSummary: "Replacement policy placeholder requiring owner review.",
    thumbnailTone: "bg-[#f1e6dd]",
    thumbnail: "/product-art/product-netflix-standard.png",
    thumbnailAlt: "Brand-neutral streaming subscription thumbnail with generic screen and play motif",
    brandKind: "netflix",
    brandLabel: "NETFLIX",
    brandColor: "#E50914",
    brandBackground: "#111111",
    brandTextColor: "#E50914",
    icon: "play",
  },
  {
    id: "netflix-premium",
    name: "Netflix Premium",
    provider: "Streaming",
    price: "Price TBA",
    billingPeriod: "month",
    badge: "Placeholder",
    shortDescription: "Premium streaming tier placeholder with owner-reviewed pricing.",
    description: "A premium streaming subscription listing template. Replace placeholder copy with finalized availability, delivery, and policy terms.",
    rating: 5,
    ratingCount: 35,
    soldQuantity: 117,
    stockQuantity: 18,
    features: ["Monthly access", "Premium tier placeholder", "Delivery support", "Replacement policy summary"],
    whatYouGet: "Plan access details after payment verification, subject to owner-confirmed terms.",
    deliveryNote: "Delivery timing and availability must be confirmed before publishing.",
    refundSummary: "Replacement policy placeholder requiring owner review.",
    thumbnailTone: "bg-[#eadfd6]",
    thumbnail: "/product-art/product-netflix-premium.png",
    thumbnailAlt: "Brand-neutral premium streaming subscription thumbnail with abstract media tiles",
    brandKind: "netflix",
    brandLabel: "NETFLIX",
    brandColor: "#E50914",
    brandBackground: "#111111",
    brandTextColor: "#E50914",
    icon: "play",
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    provider: "Streaming",
    price: "Price TBA",
    billingPeriod: "month",
    badge: "On request",
    shortDescription: "Ad-free video and music access listing ready for final pricing.",
    description: "A YouTube Premium subscription placeholder for customers who want a quick monthly setup.",
    rating: 5,
    ratingCount: 57,
    soldQuantity: 134,
    stockQuantity: 30,
    features: ["Monthly access", "Owner-reviewed pricing", "Delivery confirmation", "Support for setup questions"],
    whatYouGet: "Activation guidance and delivery notes once pricing and availability are finalized.",
    deliveryNote: "Delivered after order verification and service availability confirmation.",
    refundSummary: "Replacement policy placeholder requiring owner review.",
    thumbnailTone: "bg-[#efe9df]",
    thumbnail: "/product-art/product-youtube-premium.png",
    thumbnailAlt: "Brand-neutral video and music subscription thumbnail with generic media controls",
    brandKind: "youtube",
    brandLabel: "YouTube",
    brandColor: "#FF0000",
    brandBackground: "#ffffff",
    brandTextColor: "#0F0F0F",
    icon: "play",
  },
];

export const trustBadges = [
  { icon: "lock" as const, label: "Secure payment placeholder" },
  { icon: "shield" as const, label: "Verified seller review" },
  { icon: "refresh" as const, label: "Replacement guarantee" },
];

export const testimonials: Testimonial[] = [
  {
    id: "placeholder-1",
    name: "Placeholder Customer A",
    role: "Replace with a real customer",
    quote: "Placeholder testimonial: delivery was quick, the instructions were clear, and support answered right away.",
    rating: 5,
    avatar: "/images/subscriptions/avatar-a.png",
    avatarAlt: "Generic placeholder testimonial avatar A, to be replaced with an approved customer image",
  },
  {
    id: "placeholder-2",
    name: "Placeholder Customer B",
    role: "Replace with a real customer",
    quote: "Placeholder testimonial: the replacement policy made the purchase feel simple and low stress.",
    rating: 5,
    avatar: "/images/subscriptions/avatar-b.png",
    avatarAlt: "Generic placeholder testimonial avatar B, to be replaced with an approved customer image",
  },
  {
    id: "placeholder-3",
    name: "Placeholder Customer C",
    role: "Replace with a real customer",
    quote: "Placeholder testimonial: ordering a premium plan took just a few minutes from checkout to delivery.",
    rating: 5,
    avatar: "/images/subscriptions/avatar-c.png",
    avatarAlt: "Generic placeholder testimonial avatar C, to be replaced with an approved customer image",
  },
];

export const kpis: Kpi[] = [
  { label: "Wholesale revenue", value: "$48,290", trend: "+12.4% from last week", tone: "positive" },
  { label: "Open orders", value: "318", trend: "42 ready to fulfill", tone: "positive" },
  { label: "Reorder rate", value: "41%", trend: "18 buyers reordered", tone: "neutral" },
  { label: "Products live", value: "126", trend: "6 need inventory updates", tone: "warning" },
];

export const quickActions: QuickAction[] = [
  { label: "Add product", href: "/products/new", icon: "plus" },
  { label: "Create sale", href: "?pos=open", icon: "refresh" },
  { label: "Print labels", href: "#", icon: "printer" },
  { label: "Review orders", href: "#", icon: "wand" },
  { label: "View analytics", href: "#", icon: "analytics" },
];

export const activityItems: ActivityItem[] = [
  { id: "order-ready", title: "Order #ZV-1048 was marked ready to ship.", meta: "2 minutes ago by Julia Park" },
  { id: "draft-created", title: "New product draft created: Linen Pillow Cover.", meta: "18 minutes ago by Maya Chen" },
  { id: "sale-live", title: "Wholesale sale Early Summer Home went live.", meta: "1 hour ago by Julia Park" },
  { id: "inventory-updated", title: "Inventory updated for Amber & Moss Candle.", meta: "Yesterday at 4:12 PM" },
];

const makeImages = (id: string, image: string, alt: string) => [
  { id: `${id}-primary`, url: image, alt, primary: true },
  { id: `${id}-detail`, url: image, alt: `${alt} detail` },
];

export const products: Product[] = [
  {
    id: "earthen-vessel-04",
    name: "Earthen Vessel No. 04",
    brand: "Loom & Thread",
    sku: "LV-920",
    category: "Home Decor",
    status: "active",
    description: "Hand-thrown ceramic vessel with a soft matte glaze, designed for shelves, console styling, and floral arrangements.",
    tags: ["ceramic", "vase", "home"],
    image: "https://images.unsplash.com/photo-1602872030490-4a484a7b3ba6?auto=format&fit=crop&w=700&q=86",
    alt: "Earthen vessel in soft natural light",
    images: makeImages("earthen-vessel-04", "https://images.unsplash.com/photo-1602872030490-4a484a7b3ba6?auto=format&fit=crop&w=700&q=86", "Earthen vessel in soft natural light"),
    priceRange: "$118-$142",
    wholesalePrice: 118,
    retailPrice: 236,
    currency: "USD",
    paymentTerms: "Net 60",
    moq: 4,
    stock: 42,
    variants: [
      { id: "cream", name: "Glaze", option: "Cream", sku: "LV-920-CRM", stock: 18, priceAdjustment: 0, active: true },
      { id: "sand", name: "Glaze", option: "Sand", sku: "LV-920-SND", stock: 14, priceAdjustment: 12, active: true },
      { id: "charcoal", name: "Glaze", option: "Charcoal", sku: "LV-920-CHR", stock: 10, priceAdjustment: 24, active: true },
    ],
    weight: "3.4 lb",
    dimensions: { length: "8", width: "8", height: "11", unit: "in" },
    leadTime: "Ships in 5-7 business days",
    origin: "Portland, OR",
    returnPolicy: "Returns accepted within 14 days for unused wholesale units.",
    featured: true,
    seoTitle: "Earthen Vessel No. 04 by Loom & Thread",
    seoDescription: "A refined handmade ceramic vessel for modern retailers.",
  },
  {
    id: "organic-cotton-throw",
    name: "Organic Cotton Throw",
    brand: "Nordic Hues",
    sku: "NH-042",
    category: "Home Decor",
    status: "low-stock",
    description: "A heavyweight organic cotton throw with a soft washed finish and generous drape for home and gift retailers.",
    tags: ["textile", "throw", "organic"],
    image: "https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=700&q=86",
    alt: "Organic cotton throw in deep green",
    images: makeImages("organic-cotton-throw", "https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=700&q=86", "Organic cotton throw in deep green"),
    priceRange: "$74-$96",
    wholesalePrice: 74,
    retailPrice: 148,
    currency: "USD",
    paymentTerms: "Net 60",
    moq: 6,
    stock: 4,
    variants: [
      { id: "sage", name: "Color", option: "Sage", sku: "NH-042-SGE", stock: 2, priceAdjustment: 0, active: true },
      { id: "moss", name: "Color", option: "Moss", sku: "NH-042-MOS", stock: 2, priceAdjustment: 8, active: true },
      { id: "oat", name: "Color", option: "Oat", sku: "NH-042-OAT", stock: 0, priceAdjustment: 0, active: false },
    ],
    weight: "2.2 lb",
    dimensions: { length: "60", width: "50", height: "1", unit: "in" },
    leadTime: "Ships in 3-5 business days",
    origin: "Asheville, NC",
    returnPolicy: "Final sale on opened textiles. Unopened units may be returned within 10 days.",
    featured: false,
    seoTitle: "Organic Cotton Throw by Nordic Hues",
    seoDescription: "Organic cotton throws in refined neutral colors.",
  },
  {
    id: "articulated-brass-lamp",
    name: "Articulated Brass Lamp",
    brand: "Lumen Studio",
    sku: "LS-881",
    category: "Home Decor",
    status: "active",
    description: "A compact brass lamp with a slender profile, warm tone, and adjustable arm for counter displays and desks.",
    tags: ["lighting", "brass", "desk"],
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=700&q=86",
    alt: "Articulated brass lamp detail",
    images: makeImages("articulated-brass-lamp", "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=700&q=86", "Articulated brass lamp detail"),
    priceRange: "$245-$295",
    wholesalePrice: 245,
    retailPrice: 490,
    currency: "USD",
    paymentTerms: "Net 60",
    moq: 2,
    stock: 12,
    variants: [
      { id: "brushed", name: "Finish", option: "Brushed Brass", sku: "LS-881-BRS", stock: 8, priceAdjustment: 0, active: true },
      { id: "antique", name: "Finish", option: "Antique Brass", sku: "LS-881-ANT", stock: 4, priceAdjustment: 50, active: true },
    ],
    weight: "5.1 lb",
    dimensions: { length: "16", width: "7", height: "22", unit: "in" },
    leadTime: "Ships in 7-10 business days",
    origin: "Brooklyn, NY",
    returnPolicy: "Returns accepted within 14 days in original packaging.",
    featured: true,
    seoTitle: "Articulated Brass Lamp by Lumen Studio",
    seoDescription: "A refined brass lamp for design-led shops.",
  },
  {
    id: "pantry-vessel-set",
    name: "Pantry Vessel Set",
    brand: "Kitchen Archetype",
    sku: "KA-102",
    category: "Food & Drink",
    status: "active",
    description: "Stackable pantry vessels with airtight lids, sold as a wholesale set for kitchen, gift, and home stores.",
    tags: ["kitchen", "storage", "pantry"],
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=700&q=86",
    alt: "Pantry vessel set on a shelf",
    images: makeImages("pantry-vessel-set", "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=700&q=86", "Pantry vessel set on a shelf"),
    priceRange: "$48-$62",
    wholesalePrice: 48,
    retailPrice: 96,
    currency: "USD",
    paymentTerms: "Net 60",
    moq: 8,
    stock: 156,
    variants: [
      { id: "small", name: "Set", option: "Small Set", sku: "KA-102-S", stock: 62, priceAdjustment: 0, active: true },
      { id: "large", name: "Set", option: "Large Set", sku: "KA-102-L", stock: 94, priceAdjustment: 14, active: true },
    ],
    weight: "1.8 lb",
    dimensions: { length: "10", width: "7", height: "6", unit: "in" },
    leadTime: "Ships in 2-4 business days",
    origin: "Chicago, IL",
    returnPolicy: "Returns accepted for unused sets within 14 days.",
    featured: false,
    seoTitle: "Pantry Vessel Set by Kitchen Archetype",
    seoDescription: "Wholesale pantry vessels for refined kitchen merchandising.",
  },
  {
    id: "midnight-cedar-candle",
    name: "Midnight Cedar Candle",
    brand: "Aura Botanics",
    sku: "AB-540",
    category: "Beauty",
    status: "active",
    description: "Amber glass candle poured with cedar, smoke, and soft resin notes. Designed for gifting and home fragrance assortments.",
    tags: ["candle", "fragrance", "gift"],
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=700&q=86",
    alt: "Midnight cedar candle in amber glass",
    images: makeImages("midnight-cedar-candle", "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=700&q=86", "Midnight cedar candle in amber glass"),
    priceRange: "$36-$48",
    wholesalePrice: 36,
    retailPrice: 72,
    currency: "USD",
    paymentTerms: "Net 60",
    moq: 12,
    stock: 89,
    variants: [
      { id: "8oz", name: "Size", option: "8 oz", sku: "AB-540-8", stock: 54, priceAdjustment: 0, active: true },
      { id: "12oz", name: "Size", option: "12 oz", sku: "AB-540-12", stock: 35, priceAdjustment: 12, active: true },
    ],
    weight: "1.1 lb",
    dimensions: { length: "3", width: "3", height: "4", unit: "in" },
    leadTime: "Ships in 3-5 business days",
    origin: "Austin, TX",
    returnPolicy: "Returns accepted on unopened candles within 10 days.",
    featured: true,
    seoTitle: "Midnight Cedar Candle by Aura Botanics",
    seoDescription: "A warm cedar candle for elevated gift assortments.",
  },
];
